environment: local
deployment:
  replicas: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
image:
  repository: danors/next-face-detection
  tag: latest
  pullPolicy: Always
service:
  type: NodePort
  port: 80
  targetPort: 3000
