environment: production
deployment:
  replicas: 2
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
image:
  repository: danors/next-face-detection
  tag: latest
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
  targetPort: 3000
