apiVersion: v1
kind: Service
metadata:
  name: face-detection-service
spec:
  type: LoadBalancer
  selector:
    app: face-detection
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
