apiVersion: v1
kind: Service
metadata:
  name: face-detection-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30182
      protocol: TCP
  selector:
    app: face-detection
