name: Quality Checks and Docker Build

on:
  push:
    branches:
      - main
    paths:
      - "next-face-detection-app/**"
  pull_request:
    paths:
      - "next-face-detection-app/**"
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: next-face-detection-app

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: next-face-detection-app/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check
        run: yarn type-check
        continue-on-error: false

      - name: Lint
        run: |
          yarn lint > lint-results.txt || {
            if grep -q "Error:" lint-results.txt; then
              echo "❌ Linting errors found"
              exit 1
            else
              echo "⚠️ Linting warnings found, but continuing..."
              exit 0
            fi
          }
        continue-on-error: true

      - name: Format check
        run: yarn format --check
        continue-on-error: false

      - name: Build check
        run: yarn build
        continue-on-error: false

  docker:
    needs: quality
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' # Only run on main branch pushes
    defaults:
      run:
        working-directory: next-face-detection-app

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: danors
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./next-face-detection-app
          push: true
          tags: |
            danors/next-face-detection:latest
            danors/next-face-detection:${{ github.sha }}
          cache-from: type=registry,ref=danors/next-face-detection:buildcache
          cache-to: type=registry,ref=danors/next-face-detection:buildcache,mode=max
