name: Trigger Submodule Update

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment repo workflow
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/DanorSODA/Devops-Course-Final-Project/dispatches \
            -d '{"event_type":"update-submodule","client_payload":{"ref":"${{ github.ref }}","sha":"${{ github.sha }}"}}'
