name: Trigger Submodule Update

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
        with:
          token: ${{ env.PAT }}
          repository: DanorSODA/Devops-Course-Final-Project
          event-type: update-submodule
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
