name: Trigger Submodule Update

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Trigger deployment repo workflow
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ env.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/DanorSODA/Devops-Course-Final-Project/dispatches \
            -d '{"event_type":"update-submodule"}'
